CC=g++
main: main.cpp quicksortLMT.cpp quicksortLMT.h quicksortLST.cpp quicksortLST.h RadixSortLMT.cpp RadixSortLMT.h RadixSortLST.cpp RadixSortLST.h
        $(CC) -O3 -o main main.cpp quicksortLMT.cpp quicksortLST.cpp RadixSortLMT.cpp RadixSortLST.cpp -lpthread