CC=g++
main: main.cpp quicksortLMT.cpp quicksortLMT.h quicksortLST.cpp quicksortLST.h RadixSortLMT2.cpp RadixSortLMT2.h RadixSortLST.cpp RadixSortLST.h
	$(CC) -O3 -o main main.cpp quicksortLMT.cpp quicksortLST.cpp RadixSortLMT2.cpp RadixSortLST.cpp -lpthread